import type { CollectionEntry } from "astro:content";

type DocEntry = CollectionEntry<"docs">;

export interface NavLink {
  type: "link";
  label: string;
  href: string;
  slug: string;
  isCurrent: boolean;
  isActive: boolean;
}

export interface NavGroup {
  type: "group";
  label: string;
  href?: string;
  slug?: string;
  collapsed?: boolean;
  children: NavItem[];
  isCurrent: boolean;
  isActive: boolean;
}

export type NavItem = NavLink | NavGroup;

export interface SidebarSection {
  label: string;
  collapsed?: boolean;
  items: NavItem[];
  isActive: boolean;
}

interface AutogenerateConfig {
  directory: string;
}

export interface SidebarItemConfig {
  label?: string;
  link?: string;
  items?: SidebarItemConfig[];
  autogenerate?: AutogenerateConfig;
  collapsed?: boolean;
}

export interface SidebarSectionConfig extends SidebarItemConfig {
  label: string;
  items?: SidebarItemConfig[];
}

const normalizeDirectory = (value: string) =>
  value.replace(/^\/+/, "").replace(/\/+$/, "");

const normalizeHref = (href: string) => {
  if (!href.startsWith("/")) return href;
  return href.endsWith("/") ? href : `${href}/`;
};

export const slugToHref = (slug: string) =>
  slug === "index" || slug === ""
    ? "/docs/"
    : `/docs/${slug.replace(/^\//, "")}/`;

const titleFromSegment = (segment: string) =>
  segment.replace(/[-_]+/g, " ").replace(/\b\w/g, (char) => char.toUpperCase());

export const titleFromEntry = (entry: DocEntry) =>
  entry.data.title ??
  titleFromSegment(entry.slug.split("/").at(-1) ?? entry.slug);

const createNavLink = (entry: DocEntry): NavLink => ({
  type: "link",
  label: titleFromEntry(entry),
  href: slugToHref(entry.slug),
  slug: entry.slug,
  isCurrent: false,
  isActive: false,
});

type SidebarAccumulator = NavItem[];

const compareLabels = (a: string, b: string) =>
  a.localeCompare(b, undefined, { numeric: true, sensitivity: "base" });

const buildSubtree = (
  entries: DocEntry[],
  baseSegments: string[],
): NavItem[] => {
  let indexEntry: DocEntry | undefined;
  const childrenBySegment = new Map<string, DocEntry[]>();

  for (const entry of entries) {
    const segments = entry.slug.split("/");
    if (!baseSegments.every((segment, index) => segments[index] === segment)) {
      continue;
    }

    const rest = segments.slice(baseSegments.length);
    if (rest.length === 0) {
      indexEntry = entry;
      continue;
    }

    const [head] = rest;
    const bucket = childrenBySegment.get(head);
    if (bucket) {
      bucket.push(entry);
    } else {
      childrenBySegment.set(head, [entry]);
    }
  }

  const items: SidebarAccumulator = [];

  if (indexEntry) {
    items.push(createNavLink(indexEntry));
  }

  const sortedSegments = [...childrenBySegment.keys()].sort(compareLabels);

  for (const segment of sortedSegments) {
    const segmentEntries = childrenBySegment.get(segment)!;
    const segmentBase = [...baseSegments, segment];
    const childNodes = buildSubtree(segmentEntries, segmentBase);
    const segmentSlug = segmentBase.join("/");
    const directoryEntry = segmentEntries.find(
      (entry) => entry.slug === segmentSlug,
    );
    const filteredChildren = directoryEntry
      ? childNodes.filter(
          (child) =>
            !(child.type === "link" && child.slug === directoryEntry.slug),
        )
      : childNodes;

    items.push({
      type: "group",
      label: directoryEntry
        ? titleFromEntry(directoryEntry)
        : titleFromSegment(segment),
      href: directoryEntry ? slugToHref(directoryEntry.slug) : undefined,
      slug: directoryEntry?.slug ?? segmentSlug,
      collapsed: true,
      children: filteredChildren,
      isCurrent: false,
      isActive: false,
    });
  }

  return items;
};

const resolveAutogenerated = (
  entries: DocEntry[],
  directory: string,
): NavItem[] => {
  const normalized = normalizeDirectory(directory);
  const baseSegments = normalized ? normalized.split("/") : [];
  const relevant = entries.filter((entry) =>
    baseSegments.every(
      (segment, index) => entry.slug.split("/")[index] === segment,
    ),
  );

  if (relevant.length === 0) {
    return [];
  }

  const subtree = buildSubtree(relevant, baseSegments);
  const indexEntry = relevant.find((entry) => entry.slug === normalized);

  if (subtree.length === 0 && indexEntry) {
    return [createNavLink(indexEntry)];
  }

  const children = indexEntry
    ? subtree.filter(
        (item) => !(item.type === "link" && item.slug === indexEntry.slug),
      )
    : subtree;

  if (!children.length && !indexEntry) {
    return [];
  }

  return [
    {
      type: "group",
      label: indexEntry
        ? titleFromEntry(indexEntry)
        : titleFromSegment(baseSegments.at(-1) ?? directory),
      href: indexEntry ? slugToHref(indexEntry.slug) : undefined,
      slug: indexEntry?.slug ?? normalized,
      collapsed: true,
      children,
      isCurrent: false,
      isActive: false,
    },
  ];
};

const resolveSidebarItem = (
  item: SidebarItemConfig,
  entries: DocEntry[],
): NavItem[] => {
  if (item.link) {
    const href = normalizeHref(item.link);
    return [
      {
        type: "link",
        label:
          item.label ??
          titleFromSegment(href.split("/").filter(Boolean).at(-1) ?? href),
        href,
        slug: href.replace(/^\/docs\/?/, "").replace(/\/$/, "") || "index",
        isCurrent: false,
        isActive: false,
      },
    ];
  }

  if (item.items) {
    const children = item.items.flatMap((child) =>
      resolveSidebarItem(child, entries),
    );
    if (!children.length) {
      return [];
    }
    return [
      {
        type: "group",
        label: item.label ?? "Section",
        collapsed: item.collapsed,
        children,
        isCurrent: false,
        isActive: false,
      },
    ];
  }

  if (item.autogenerate) {
    const generated = resolveAutogenerated(
      entries,
      item.autogenerate.directory,
    );
    if (!generated.length) {
      return [];
    }
    if (generated.length === 1 && generated[0]?.type === "group") {
      generated[0].label = item.label ?? generated[0].label;
      generated[0].collapsed = item.collapsed ?? generated[0].collapsed;
    }
    return generated;
  }

  return [];
};

const annotateNavItem = (item: NavItem, currentHref: string): NavItem => {
  if (item.type === "link") {
    const isCurrent = normalizeHref(item.href) === currentHref;
    return { ...item, isCurrent, isActive: isCurrent };
  }

  const children = item.children.map((child) =>
    annotateNavItem(child, currentHref),
  );
  const isCurrent = item.href
    ? normalizeHref(item.href) === currentHref
    : false;
  const isActive = isCurrent || children.some((child) => child.isActive);

  return {
    ...item,
    children,
    isCurrent,
    isActive,
  };
};

export const buildSidebar = (
  entries: DocEntry[],
  sections: SidebarSectionConfig[],
  currentSlug: string,
): SidebarSection[] => {
  const currentHref = slugToHref(currentSlug);

  return sections
    .map((section) => {
      const items = section.items
        ? section.items.flatMap((child) => resolveSidebarItem(child, entries))
        : resolveSidebarItem(section, entries);

      if (!items.length) {
        return undefined;
      }

      const annotated = items.map((item) => annotateNavItem(item, currentHref));
      const isActive = annotated.some((item) => item.isActive);

      return {
        label: section.label,
        collapsed: section.collapsed,
        items: annotated,
        isActive,
      } satisfies SidebarSection;
    })
    .filter((section): section is SidebarSection => Boolean(section));
};
