import React from 'react';
import ComponentCreator from '@docusaurus/ComponentCreator';

export default [
  {
    path: '/__docusaurus/debug',
    component: ComponentCreator('/__docusaurus/debug', 'c37'),
    exact: true
  },
  {
    path: '/__docusaurus/debug/config',
    component: ComponentCreator('/__docusaurus/debug/config', '724'),
    exact: true
  },
  {
    path: '/__docusaurus/debug/content',
    component: ComponentCreator('/__docusaurus/debug/content', '234'),
    exact: true
  },
  {
    path: '/__docusaurus/debug/globalData',
    component: ComponentCreator('/__docusaurus/debug/globalData', '2d2'),
    exact: true
  },
  {
    path: '/__docusaurus/debug/metadata',
    component: ComponentCreator('/__docusaurus/debug/metadata', 'bf6'),
    exact: true
  },
  {
    path: '/__docusaurus/debug/registry',
    component: ComponentCreator('/__docusaurus/debug/registry', 'c13'),
    exact: true
  },
  {
    path: '/__docusaurus/debug/routes',
    component: ComponentCreator('/__docusaurus/debug/routes', '1af'),
    exact: true
  },
  {
    path: '/blog',
    component: ComponentCreator('/blog', '125'),
    exact: true
  },
  {
    path: '/blog/archive',
    component: ComponentCreator('/blog/archive', '301'),
    exact: true
  },
  {
    path: '/blog/tags',
    component: ComponentCreator('/blog/tags', 'a7a'),
    exact: true
  },
  {
    path: '/blog/tags/docusaurus',
    component: ComponentCreator('/blog/tags/docusaurus', '82b'),
    exact: true
  },
  {
    path: '/blog/tags/facebook',
    component: ComponentCreator('/blog/tags/facebook', '09f'),
    exact: true
  },
  {
    path: '/blog/tags/hello',
    component: ComponentCreator('/blog/tags/hello', '231'),
    exact: true
  },
  {
    path: '/blog/welcome',
    component: ComponentCreator('/blog/welcome', 'f2f'),
    exact: true
  },
  {
    path: '/markdown-page',
    component: ComponentCreator('/markdown-page', '90a'),
    exact: true
  },
  {
    path: '/community',
    component: ComponentCreator('/community', '753'),
    routes: [
      {
        path: '/community',
        component: ComponentCreator('/community', '728'),
        routes: [
          {
            path: '/community',
            component: ComponentCreator('/community', 'e82'),
            routes: [
              {
                path: '/community/deploy-your-site',
                component: ComponentCreator('/community/deploy-your-site', 'a8f'),
                exact: true,
                sidebar: "myAutogeneratedSidebar"
              },
              {
                path: '/community/intro',
                component: ComponentCreator('/community/intro', 'fb8'),
                exact: true,
                sidebar: "myAutogeneratedSidebar"
              },
              {
                path: '/community/translate-your-site',
                component: ComponentCreator('/community/translate-your-site', '5e4'),
                exact: true,
                sidebar: "myAutogeneratedSidebar"
              }
            ]
          }
        ]
      }
    ]
  },
  {
    path: '/docs',
    component: ComponentCreator('/docs', '3aa'),
    routes: [
      {
        path: '/docs',
        component: ComponentCreator('/docs', '246'),
        routes: [
          {
            path: '/docs',
            component: ComponentCreator('/docs', '144'),
            routes: [
              {
                path: '/docs/category/ascomycota',
                component: ComponentCreator('/docs/category/ascomycota', '0a1'),
                exact: true,
                sidebar: "myAutogeneratedSidebar"
              },
              {
                path: '/docs/category/basidiomycota',
                component: ComponentCreator('/docs/category/basidiomycota', 'a1e'),
                exact: true,
                sidebar: "myAutogeneratedSidebar"
              },
              {
                path: '/docs/category/blastocladiomycota',
                component: ComponentCreator('/docs/category/blastocladiomycota', '567'),
                exact: true,
                sidebar: "myAutogeneratedSidebar"
              },
              {
                path: '/docs/category/chytridiomycota',
                component: ComponentCreator('/docs/category/chytridiomycota', '5aa'),
                exact: true,
                sidebar: "myAutogeneratedSidebar"
              },
              {
                path: '/docs/category/class',
                component: ComponentCreator('/docs/category/class', 'abc'),
                exact: true,
                sidebar: "myAutogeneratedSidebar"
              },
              {
                path: '/docs/category/cultivation',
                component: ComponentCreator('/docs/category/cultivation', 'fe7'),
                exact: true,
                sidebar: "myAutogeneratedSidebar"
              },
              {
                path: '/docs/category/family',
                component: ComponentCreator('/docs/category/family', 'e49'),
                exact: true,
                sidebar: "myAutogeneratedSidebar"
              },
              {
                path: '/docs/category/genus',
                component: ComponentCreator('/docs/category/genus', '300'),
                exact: true,
                sidebar: "myAutogeneratedSidebar"
              },
              {
                path: '/docs/category/glomeromycota',
                component: ComponentCreator('/docs/category/glomeromycota', 'eba'),
                exact: true,
                sidebar: "myAutogeneratedSidebar"
              },
              {
                path: '/docs/category/morchella',
                component: ComponentCreator('/docs/category/morchella', '4de'),
                exact: true,
                sidebar: "myAutogeneratedSidebar"
              },
              {
                path: '/docs/category/morchellaceae',
                component: ComponentCreator('/docs/category/morchellaceae', 'df3'),
                exact: true,
                sidebar: "myAutogeneratedSidebar"
              },
              {
                path: '/docs/category/mucoromycota',
                component: ComponentCreator('/docs/category/mucoromycota', '5f4'),
                exact: true,
                sidebar: "myAutogeneratedSidebar"
              },
              {
                path: '/docs/category/neocallimastigomycota',
                component: ComponentCreator('/docs/category/neocallimastigomycota', '231'),
                exact: true,
                sidebar: "myAutogeneratedSidebar"
              },
              {
                path: '/docs/category/opisthosporidia',
                component: ComponentCreator('/docs/category/opisthosporidia', '3d9'),
                exact: true,
                sidebar: "myAutogeneratedSidebar"
              },
              {
                path: '/docs/category/order',
                component: ComponentCreator('/docs/category/order', '9c4'),
                exact: true,
                sidebar: "myAutogeneratedSidebar"
              },
              {
                path: '/docs/category/pezizales',
                component: ComponentCreator('/docs/category/pezizales', '548'),
                exact: true,
                sidebar: "myAutogeneratedSidebar"
              },
              {
                path: '/docs/category/pezizomycetes',
                component: ComponentCreator('/docs/category/pezizomycetes', 'dc3'),
                exact: true,
                sidebar: "myAutogeneratedSidebar"
              },
              {
                path: '/docs/category/phylum',
                component: ComponentCreator('/docs/category/phylum', 'c85'),
                exact: true,
                sidebar: "myAutogeneratedSidebar"
              },
              {
                path: '/docs/category/species',
                component: ComponentCreator('/docs/category/species', '907'),
                exact: true,
                sidebar: "myAutogeneratedSidebar"
              },
              {
                path: '/docs/category/zoopagomycotina',
                component: ComponentCreator('/docs/category/zoopagomycotina', '544'),
                exact: true,
                sidebar: "myAutogeneratedSidebar"
              },
              {
                path: '/docs/cultivation/congratulations',
                component: ComponentCreator('/docs/cultivation/congratulations', 'f67'),
                exact: true,
                sidebar: "myAutogeneratedSidebar"
              },
              {
                path: '/docs/cultivation/create-a-blog-post',
                component: ComponentCreator('/docs/cultivation/create-a-blog-post', '0e2'),
                exact: true,
                sidebar: "myAutogeneratedSidebar"
              },
              {
                path: '/docs/cultivation/create-a-document',
                component: ComponentCreator('/docs/cultivation/create-a-document', 'ac5'),
                exact: true,
                sidebar: "myAutogeneratedSidebar"
              },
              {
                path: '/docs/cultivation/create-a-page',
                component: ComponentCreator('/docs/cultivation/create-a-page', '835'),
                exact: true,
                sidebar: "myAutogeneratedSidebar"
              },
              {
                path: '/docs/cultivation/deploy-your-site',
                component: ComponentCreator('/docs/cultivation/deploy-your-site', '97c'),
                exact: true,
                sidebar: "myAutogeneratedSidebar"
              },
              {
                path: '/docs/cultivation/markdown-features',
                component: ComponentCreator('/docs/cultivation/markdown-features', '0ed'),
                exact: true,
                sidebar: "myAutogeneratedSidebar"
              },
              {
                path: '/docs/intro',
                component: ComponentCreator('/docs/intro', '643'),
                exact: true,
                sidebar: "myAutogeneratedSidebar"
              },
              {
                path: '/docs/phylum/Ascomycota/intro',
                component: ComponentCreator('/docs/phylum/Ascomycota/intro', '3f6'),
                exact: true,
                sidebar: "myAutogeneratedSidebar"
              },
              {
                path: '/docs/phylum/Ascomycota/Pezizomycetes/intro',
                component: ComponentCreator('/docs/phylum/Ascomycota/Pezizomycetes/intro', '026'),
                exact: true,
                sidebar: "myAutogeneratedSidebar"
              },
              {
                path: '/docs/phylum/Ascomycota/Pezizomycetes/Pezizales/intro',
                component: ComponentCreator('/docs/phylum/Ascomycota/Pezizomycetes/Pezizales/intro', '5b7'),
                exact: true,
                sidebar: "myAutogeneratedSidebar"
              },
              {
                path: '/docs/phylum/Ascomycota/Pezizomycetes/Pezizales/Morchellaceae/intro',
                component: ComponentCreator('/docs/phylum/Ascomycota/Pezizomycetes/Pezizales/Morchellaceae/intro', '659'),
                exact: true,
                sidebar: "myAutogeneratedSidebar"
              },
              {
                path: '/docs/phylum/Ascomycota/Pezizomycetes/Pezizales/Morchellaceae/Morchella/intro',
                component: ComponentCreator('/docs/phylum/Ascomycota/Pezizomycetes/Pezizales/Morchellaceae/Morchella/intro', 'bc4'),
                exact: true,
                sidebar: "myAutogeneratedSidebar"
              },
              {
                path: '/docs/phylum/Basidiomycota/intro',
                component: ComponentCreator('/docs/phylum/Basidiomycota/intro', 'd4a'),
                exact: true,
                sidebar: "myAutogeneratedSidebar"
              },
              {
                path: '/docs/phylum/Blastocladiomycota/intro',
                component: ComponentCreator('/docs/phylum/Blastocladiomycota/intro', '2b5'),
                exact: true,
                sidebar: "myAutogeneratedSidebar"
              },
              {
                path: '/docs/phylum/Chytridiomycota/intro',
                component: ComponentCreator('/docs/phylum/Chytridiomycota/intro', 'e44'),
                exact: true,
                sidebar: "myAutogeneratedSidebar"
              },
              {
                path: '/docs/phylum/class/intro',
                component: ComponentCreator('/docs/phylum/class/intro', 'a75'),
                exact: true,
                sidebar: "myAutogeneratedSidebar"
              },
              {
                path: '/docs/phylum/class/order/family/genus/intro',
                component: ComponentCreator('/docs/phylum/class/order/family/genus/intro', 'd5f'),
                exact: true,
                sidebar: "myAutogeneratedSidebar"
              },
              {
                path: '/docs/phylum/class/order/family/genus/species/intro',
                component: ComponentCreator('/docs/phylum/class/order/family/genus/species/intro', '507'),
                exact: true,
                sidebar: "myAutogeneratedSidebar"
              },
              {
                path: '/docs/phylum/class/order/family/intro',
                component: ComponentCreator('/docs/phylum/class/order/family/intro', '3e0'),
                exact: true,
                sidebar: "myAutogeneratedSidebar"
              },
              {
                path: '/docs/phylum/class/order/intro',
                component: ComponentCreator('/docs/phylum/class/order/intro', '702'),
                exact: true,
                sidebar: "myAutogeneratedSidebar"
              },
              {
                path: '/docs/phylum/Glomeromycota/intro',
                component: ComponentCreator('/docs/phylum/Glomeromycota/intro', '8b4'),
                exact: true,
                sidebar: "myAutogeneratedSidebar"
              },
              {
                path: '/docs/phylum/intro',
                component: ComponentCreator('/docs/phylum/intro', '919'),
                exact: true,
                sidebar: "myAutogeneratedSidebar"
              },
              {
                path: '/docs/phylum/Mucoromycota/intro',
                component: ComponentCreator('/docs/phylum/Mucoromycota/intro', 'a3f'),
                exact: true,
                sidebar: "myAutogeneratedSidebar"
              },
              {
                path: '/docs/phylum/Neocallimastigomycota/intro',
                component: ComponentCreator('/docs/phylum/Neocallimastigomycota/intro', '4b0'),
                exact: true,
                sidebar: "myAutogeneratedSidebar"
              },
              {
                path: '/docs/phylum/Opisthosporidia/intro',
                component: ComponentCreator('/docs/phylum/Opisthosporidia/intro', '00a'),
                exact: true,
                sidebar: "myAutogeneratedSidebar"
              },
              {
                path: '/docs/phylum/Zoopagomycotina/intro',
                component: ComponentCreator('/docs/phylum/Zoopagomycotina/intro', 'd3e'),
                exact: true,
                sidebar: "myAutogeneratedSidebar"
              }
            ]
          }
        ]
      }
    ]
  },
  {
    path: '/',
    component: ComponentCreator('/', '9e1'),
    exact: true
  },
  {
    path: '*',
    component: ComponentCreator('*'),
  },
];
